baseURL = 'https://personlin.github.io/portal/'
languageCode = 'zh-tw'
title = 'Portal'
# This is a GitHub Project Pages site (https://personlin.github.io/portal/)
# so we must set the correct base path.
canonifyURLs = true
relativeURLs = false

theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true

[params]
  description = 'Personal portal'
  defaultTheme = 'auto'
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = 'Portal'
    Content = 'Welcome. Use the menu for Links and Notes.'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = ''
    weight = 1
  [[menu.main]]
    identifier = 'links'
    name = 'Links'
    url = 'links/'
    weight = 2
  [[menu.main]]
    identifier = 'notes'
    name = 'Notes'
    url = 'notes/'
    weight = 3
